title: "AI Assisted Programming"
description: >-
  News about AI tools for programming
baseurl: "/rss-digest-blog"  # the subpath of your site, e.g. /blog
url: "https://marcbln.github.io"  # your GitHub Pages URL
github_username: marcbln

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
